
import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tony
 */
public class Interfaz extends javax.swing.JFrame {
    
    Asociacion_Vecinos av;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        av =new Asociacion_Vecinos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        anuncio = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prueba 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jButton3.setText("Vecino");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButton4.setText("Cargar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, -1));

        jButton5.setText("Apartamento del vecino");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, -1));

        jButton6.setText("Edificio del apartamento");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jButton7.setText("Direccion del vecino");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, -1));
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 360, -1));

        anuncio.setForeground(new java.awt.Color(0, 255, 0));
        jPanel1.add(anuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo5.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        av.VaciarTodo();
        av.CargarDatos();
        av.Ordenar_Vecinos(av);
        anuncio.setText("Se han cargado los datos");
        anuncio.setForeground(new Color(0,255,0));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        try{
            anuncio.setText("");
            
            long cedula_b = Long.parseLong(input.getText());
            
            av.Direccion_Vecino(cedula_b);
            
            anuncio.setText("Se ha hecho la operacion exitosamente");
            anuncio.setForeground(new Color(0,255,0));
            
        }catch(Exception e){
            anuncio.setText("no ha puesto una cedula o cargado los datos");
            anuncio.setForeground(new Color(255,0,0));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try{
            anuncio.setText("");
            
            int cedula_b = Integer.parseInt(input.getText());
            
            Vecinos aux =av.Buscar_Vecino(cedula_b);
            
            if(aux != null){
            
                JOptionPane.showMessageDialog(null, aux.Imprimir());

                anuncio.setText("Se ha hecho la operacion exitosamente");
                anuncio.setForeground(new Color(0,255,0));
            }
            
            else{
        
                JOptionPane.showMessageDialog(null, "No se ha encontrado un vecino con esa cedula");

                anuncio.setText("Se ha hecho la operacion exitosamente");
                anuncio.setForeground(new Color(0,255,0));
            }
            
        }catch(Exception e){
            anuncio.setText("no ha puesto una cedula o cargado los datos");
            anuncio.setForeground(new Color(255,0,0));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try{
            anuncio.setText("");
            
            int cedula_b = Integer.parseInt(input.getText());
            
            Vecinos aux =av.Buscar_Vecino(cedula_b);
            
            if(aux != null){
            
                Apartamentos temp=av.Buscar_Apartamento(aux);

                JOptionPane.showMessageDialog(null, temp.Imprimir());

                anuncio.setText("Se ha hecho la operacion exitosamente");
                anuncio.setForeground(new Color(0,255,0));
            }
            
            else{
            
                JOptionPane.showMessageDialog(null, "No se ha encontrado un vecino con esa cedula");

                anuncio.setText("Se ha hecho la operacion exitosamente");
                anuncio.setForeground(new Color(0,255,0));
            }
            
        }catch(Exception e){
            anuncio.setText("no ha puesto una cedula o cargado los datos");
            anuncio.setForeground(new Color(255,0,0));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        try{
            
            String numero =input.getText().toUpperCase();
            
            String Mensaje ="Los edificios encontrados con la etiqueta "+numero+" son:\n\n";
                    
            anuncio.setText("");

            Apartamentos[] aux = av.Busqueda_Apartamento(numero);
            
            if(aux[0] !=null){
            
                for (int i = 0; i < aux.length; i++) {
                
                if(aux[i] != null){
                
                    Edificio temp = av.Buscar_Edificio_Apartamento(aux[i]);
                    
                    Mensaje +=temp.Imprimir();
                    
                    Mensaje += "\n\n";
                    }
                }
                
                JOptionPane.showMessageDialog(null, Mensaje);
                anuncio.setText("Se ha hecho la operacion exitosamente");
                anuncio.setForeground(new Color(0,255,0));
            }
            
            else{
            
            JOptionPane.showMessageDialog(null, "No se ha encontrado el edificio de ese departamento o cargado los datos");
            anuncio.setText("Se ha hecho la operacion exitosamente");
            anuncio.setForeground(new Color(0,255,0));
            }

        }catch(Exception e){
            anuncio.setText("no ha ingresado un numero de apartamento o cargado los datos");
            anuncio.setForeground(new Color(255,0,0));
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anuncio;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
